### ISSUE TITLE
Auto-clicker seems to have been added in one of the latest updates

### ISSUE THREAD

**Issue by Kline-** [mouseas/steamSummerMinigame#79]
Got the update redirect in TamperMonkey and...There now seems to be auto-clicking going on. What gives?

**Comment by win0na** [comment]
If you are running 2.0 or later, this is the current disclaimer. Pay attention to the last part.

![ss 2015-06-13 at 08 31 21](https://cloud.githubusercontent.com/assets/4269491/8146648/42b8a894-120b-11e5-9126-09533211e88f.png)

**Comment by Kline-** [comment]
That seems pretty contradictory...Saying there won't be an autoclicker yet still having one only in certain situations. Well, it had a good run. Back to no script then I guess.

**Comment by win0na** [comment]
It is not meant to be contradictory. If it is, then I can reword it. The point of this script is to optimize gold retrieval. Normal clicking (thus normal autoclicking) does not give you extra gold. Only when the monster dies is when you receive gold, and even then, everyone in the lane receives the gold, thus rendering normal autoclicking pointless.

However, whenever raining gold / gold rain is running, the script is not longer "optimal" because you gain gold when clicking. That is the reason why it autoclicks _only_ when gold rain is present.

**Comment by AlexLeporiday** [comment]
Would you please add a toggle somewhere to disable any and all auto-clicks and item uses?
I like the lane switching feature but I prefer to manually drive the clicking and item use.

**Comment by ghost** [comment]
I can do this tomorrow, the toggle functionality is already added in the [SteamDatabase](https://github.com/SteamDatabase/steamSummerMinigame) fork so it should be easy to implement.

Also, we should start cherry-picking some of their stuff to integrate back in. Some nice stuff like their `s()` function instead of typing `g_Minigame.m_CurrentScene` all the time, plus they've already got `useTreasureIfRelevant()` and `useMaxElementalDmgIfRelevant()` implemented; saves us time implementing this stuff. New issue maybe?

**Comment by mouseas** [comment]
I've removed the disclaimer. Given that performance in-game has next to no effect out-of-game, I doubt Valve will care to crack down on auto-clickers. I also realize this script is very much a cheat, with or without an auto-clicker.
