### ISSUE TITLE
When should Cripple Monster be used?

### ISSUE THREAD

**Issue by sktan** [mouseas/steamSummerMinigame#89]
Should it be used on bosses (which reduces the optimal gold earning per boss-fight) and also goes against the strategy guides used by nearly everyone.
Or should it be used on spawners when the CRIPPLE_SPAWNER item can't be currently used.

**Comment by ghost** [comment]
I'd say spawners, as the bosses go down fast enough as is. Also, we need to look into mass spamming abilities near the end of the day to get some use out of them

**Comment by mouseas** [comment]
I'd say use it on minibosses, but only if not Raining Gold.

EDIT: To expand on this, I'd say most abilities should be reserved for boss levels, either for the boss (if the ability helps get money) or the minibosses (if it does damage). I think this because the cooldown for abilities is longer than the amount of time it takes to go through 10 levels.
