### ISSUE TITLE
Unnecessary weapon upgrades

### ISSUE THREAD

**Issue by owah** [mouseas/steamSummerMinigame#93]
hi,

is there any reason why the script should go above level 10 of each weapons upgrade, except for the endgame weapons (AFK clicker and NMB currently)?

I mean at some point a 10 damage increase costs as much as a 10,000 would. its just not right.

**Comment by luxzg** [comment]
Just came to post this too. I have 31x Auto-fire cannon, and 48x Armor piercing rounds. And if I hadn't clicked manually upgrades for higher level upgrades I'd probably have a ton of those two without ever getting e.g. Railgun.

Perfect upgrade path is 10x -> than 10x of next level -> 10x of next level, than calculate the $/DPC ratio for weapons or $/health gain ratio for shields.

Also, I think script never purchased any shields, which is a shame. Early in game if you get to Energy Shields you're practically in eternal God Mode now when everyone throws Medics whenever they can.

Also, I just got this, there's a new upgrade level, I see "New Mouse Button" after Railgun, so probably some added after others as well. So in any way just go to 10x each level, untill you get to the highest level available, as owah already suggested.

And perhaps adding something like this on top of script, for those that prefer manual upgrading:
var autoBuyUpgrades = false; // (true/false)

EDIT: one more thing. Script shouldn't be allowed to buy with 100% budget (or close to that). E.g. if autoupgrades is enabled and I wait for a new upgrade on 120M gold, and if script has priority upgrade on that lvl it will buy before I even see 120M number on the screen. Perhaps adding a variable how much % of the budget script has available? E.g. this now is 100%, and if I want it to wait till it can buy with 80% of whole amount, in this case it would wait till 150M is in my coffers so it has 120M to spend (80%). Just a suggestion though

**Comment by gapple** [comment]
At some point, cheaper weapons provide more damage per gold spent.
Roughly if the lesser item is cheaper than 1/10 of the cost of the greater item, it is a better value.

In my game this morning before it ended:

| Item | Current Level | +DPS | Cost to Upgrade | +DPS / Gold | Order of value |
| --- | --- | --- | --- | --- | --- |
| Auto-fire Canon | 56 | 10 | 360M | 2.777777778e-08 | 4 |
| Advanced Targeting | 16 | 100 | 3 011M | 3.321155762e-08 | 2 |
| Farming Equipment | 16 | 1 000 | 30 113M | 3.320824893e-08 | 3 |
| AFK Equipment | 16 | 10 000 | 301B | 3.322259136e-08 | 1 |

So AFK Equipment is the best value that it's saving for by a small margin, but once purchased the price will increase to make both Advanced Targeting and Farming equipment better value.

**Comment by luxzg** [comment]
True, but not early on. There's absolutely no cost benefit of buying 48x Armor Piercing vs ZERO of Explosive Rounds (or Railgun/New Mouse Button abilities, which never unlock due to zero Explosive Rounds)

**Comment by gapple** [comment]
I think the first level items are the one exception, since they have a smaller rate of price increase than later rounds (1.3 versus 2.2).

At the moment for auto-fire upgrades I have levels 35 / 10 / 10 / 9.
All first level upgrades so far cost a total of 6M, while the level 9 upgrade for fourth level was 584M.  That is a small delay towards fully upgrading later items, and provides a (small) DPS advantage in the mean time.

**Comment by gapple** [comment]
And armour is only purchased when health is low (< 30%).  With people throwing medics frequently, health stays high and more armour is not really needed, even though it is cheap.

**Comment by RaeveNoir** [comment]
The Gold to Stat ratio seems to be working correctly, but it really needs to be rushing to unlock the next tier instead of buying the 'most efficient' stat.

The first upgrade of Tier 3 is a measly 10k gold. Shouldn't spend 1.2 million on the Tier 1 just because it's more efficient than Tier 2.

Similar to this, health should be bought before just about anything, and rushed in the same manner. The script was buying 100hp for millions when it could have bought rank 10 in Tier 2 and paid 10k to double my HP.

**Comment by enygma999** [comment]
Looking at total cost/dps for the weapons upgrades might be better in terms of mid-term efficiency - I've had a look at the auto-fire upgrades and the most efficient combination according to my analysis is 21-10-10-10-6. I haven't looked at the click upgrades yet, but expect they'll be similar. I think the code should be aiming to get to these stats (possibly taking the most efficient upgrade that doesn't go beyond these) and then going for the most efficient upgrades after that point, as anything beyond those levels will be less efficient in terms of overall money spent vs dps.

**Comment by mouseas** [comment]
Yeah, upgrades need to take unlocking into account; for each of the tiered upgrades, it should always aim for level 10 in each tier before considering DPS at all.

**Comment by enygma999** [comment]
Agreed. As a side note related to my previous post, the most efficient click upgrade level is 29-10-10-10-6. The best system would probably buy each tier to level 10, then the final tier to level 6, then the first tier up to level 29 before caring about purchase efficiency. I'd code it up, but my code tends to be horrible and not fit for group use :/

**Comment by mouseas** [comment]
@enygma999 Great, I look forward to it. For health, make sure it's still only buying health if current HP is below 30%; that's in place to avoid buying hp upgrades that aren't needed.

**Comment by RaeveNoir** [comment]
I don't agree with only buying health when "needed", because then it gets into this terrible loop around level 500 or so of being dead within seconds but not having Tier 3 unlocked yet and never getting enough money to finish Tier 2. I had to manually spam it up to unlock Tier 3 and just a few points went from 100k health to 750k and no more issue.

If anything, the threshold to buy health should be more like <75%. The less total health you have, the easier it is for enemy damage to outpace using Medics.

**Comment by Ruzihm** [comment]
So only buy when both:
1. your health is below some threshold, and
2. you have enough money to afford the most (immediately) price:bonus
efficient health buy of the health items are available.

Sometimes, you might just die because you can't afford the best value
health item.

Either way, you'll eventually get to the point that getting the 10th tier2
health item is cheaper han 10x the price of the tier 1 health item

**Comment by mouseas** [comment]
@Ranzear Good point. Maybe only consider having <50% hp after you have unlocked the 3rd tier of health upgrades; before unlocking tier 3 health, buying health upgrades has a higher priority and auto-purchaser upgrades each tier to 10.

**Comment by ghost** [comment]
I think we talked in another thread somewhere about reserving cash for lucky upgrades/boss loot and stuff; maybe this could fall into that reserve?

**Comment by mouseas** [comment]
@JCKE do you mean reserving some money so that the player can manually purchase health, or so that the auto purchaser always has enough to buy the next health upgrade?

Actually, come to think of it, reserving enough to buy the next health upgrade sounds like a good policy to determine how much to reserve. Any volunteers to implement this?

**Comment by mouseas** [comment]
@russeli implemented reserving enough gold to buy a health upgrade. We still need to adjust auto buy code to get 10 in each tier before upgrading according DPS/gold, though. Any takers?

**Comment by mouseas** [comment]
Just discovered that buying ANY health upgrade will refill your hp, so buying the least expensive upgrade when hp is low might be a viable strategy once the top tier is unlocked.

**Comment by ghost** [comment]
How about some sort of system that takes into account the last time you got near death? If it detects a high frequency it will halt spending on weapons and start going for health.

**Comment by ghost** [comment]
@mouseas Also, and I know you've stated your stance on this before, but would it really hurt to add an optional autoclick now? It would just be another box to toggle on and off.

**Comment by mouseas** [comment]
Not really. I realized on day 2 that it was a cheat script regardless of auto-clicking, and by day 3 it was clear no amount of cheating in-game was going to affect Valve negatively. As far as UI goes for auto-clicking, Since auto-clicking is off if clickrate is 0, we only need an option for "gold rain only" (with the false case being always-on).

Also, I fully agree on watching for frequent near-deaths and prioritizing health if several have happened recently.
