### ISSUE TITLE
Disable "Throw Money At Screen"

### ISSUE THREAD

**Issue by luxzg** [mouseas/steamSummerMinigame#94]
Since this is the "gold retrieval script" it would be logical that this ability is also disabled once we have Boss in the lane. Actually, I'd disable it altogether, since it's useless, but oh well.

I've tried adding this, but seems to take no effect:

 disableAbility(ABILITIES.THROW_MONEY);

**Comment by ghost** [comment]
Problem is it's an item, not an ability

**Comment by Chdata** [comment]
Rather, why don't we all spam it during the last hour or two. By then our upgrades will probably be way too high to even buy, so what other use would our gold have?

Worm holes should probably also be autospammed at that time too. Since bosses only get slower and slower over time, the longer we wait the more use we're getting out of it.

**Comment by mouseas** [comment]
Done. See commit 21b58ebc945e27bb0b7e5c6a39320e72643fb01c
